

	<div class="container-fluid">
		<div class="messageE message row">
		       
	             <?php         
	         
	             if(empty($_SESSION['messageCM'])==false)
	             {
	             	echo "<p class='green'>".$_SESSION['messageCM'].'</p>'; 

		             $_SESSION['messageCM']=null; 
	             }
	       
		        if(empty($_SESSION['erreur'])==false)
	            	foreach ($_SESSION['erreur']as $key => $value)
	            	{
	            		echo '<p>'.$value.'</p>'; 
	            		$_SESSION['erreur']=null; 

	            	}    
		        
		                     
	             ?>

	  	  </div>	
        <div>
        	<div class="row titreG">
				<h2 >Vous pouvez changer  votre mot de passe </h2>
			</div>

		
			<form action="gerer.php" method="POST" >
                
            <div class="row paddingdix"> 
            	<div class="col-md-2"></div>
            	<div class=" col-xs-12 col-md-3 ">
					<label for="oldPassword" id="bouge1"  >Ancien mot de passe </label>
				</div>
				<div class=" col-xs-12 col-md-3 ">
					<input type="password" name="oldPassword" maxlength="12" minlength="6"  class="form-control">
				</div>
				<div class="col-md-3"></div>
			</div>	
			
			<div class="row paddingdix">
				<div class="col-md-2"></div>
				<div class=" col-xs-12 col-md-3 ">
					<label for="newPassword" id="bouge2"> Nouveau mot de passe </label>
				</div>
				<div class=" col-xs-12 col-md-3 ">
					<input type="password" name="newPassword"  maxlength="12" minlength="6" class="form-control">
				</div>
				<div class="col-md-3"></div>
			</div>	
			<div class="row paddingdix">
				<div class="col-md-2"></div>
				<div class=" col-xs-12 col-md-3 ">
		       		 <label for="rNewPassword"> Répétez le nouveau mot de passe </label>
		       </div>
		       <div class=" col-xs-12 col-md-3 ">		 
					<input type="password" name="rNewPassword" maxlength="12" minlength="6" class="form-control">
				</div>
				<div class="col-md-3"></div>
			</div>

			<div class="row paddingdix" style="padding-bottom: ">
				<div class="col-xs-5"></div>
				<div class="col-xs-4">	
					<input type="submit" name="submit" value="Enregistrer" onclick="message()" id="bouge3" class="btn btn-warning subchangeM">
				</div>
				<div class="col-xs-3"></div>	
			</div>				
			</form>
		
		</div>
				        <!-- messages:-->
		
	</div>

<!-- javascript-->
<script type="text/javascript">
		function message()
		{



          if(confirm("Voulez-vous vraiment modifier votre mot de passe ?"))
          {
           	var v=1;
           	 
          }
          if(v!==1)
          {
          	document.write("Vous avez renoncé à enregistrer !");
          	
          	setTimeout(function() {window.location.assign("gerer.php");},2500);             	
          	        	
          }	 
		}
        
	</script>