<div >
  <div class="row info">
        <div class="col-xs-12 col-md-5 ">
      <div id="img1" class="img1">

        <img  src=<?=$annonceDetail[0]['url']?> style=" width:100%;" title='<?=$annonceDetail[0]['name'].', '.$sex.' '.$typeA.' le ' .$annonceDetail[0]['datePT'] ?>'>
      </div>

      <div class="contact">
      
          <h5><?=$messageContact?></h5>
          <p>
               Téléphone :
               <span>  <?=$annonceDetail[0]['phone']?></span>
          </p>
      
      </div>

      </div>   
      
        
    <div class="col-xs-12 col-md-7 detail" >
        <div  style="width: 100%; " >
          <h4 id="cap" ><?=$annonceDetail[0]['name'].', '?> <?=$sex.' '?><?=$typeA?> </h4>
          
            <div class="rowD" >
              <label class="col-xs-4">Publié le </label>
              <td class="col-xs-8"><?=$datePublie?></td>
            </div>
            <div class="rowD" >
              <label class="col-xs-4">Sexe </label>
              <td class="col-xs-8"><?php if($annonceDetail[0]['sex']=='male') echo 'mâle'; else echo $annonceDetail[0]['sex']; ?></td>
            </div>
            <div class="rowD" >
              <label class="col-xs-4">Race </label>
              <td class="col-xs-8"><span id=Minuscule><?=$annonceDetail[0]['race']?></span></td>
            </div>
            <div class="rowD" >
              <label class="col-xs-4">Couleur </label>
              <td><?=$annonceDetail[0]['couleurs']?></td class="col-xs-8">
            </div>

            <div class="rowD" >
              <label class="col-xs-4">Poils </label>
              <td class="col-xs-8"><?=$annonceDetail[0]['poils']?></td>
            </div>
            <div class="rowD" >
              <label class="col-xs-4">Pelage </label>
              <td class="col-xs-8"><?=$annonceDetail[0]['pelage']?></td>
            </div>

            <div class="rowD" >
              <label class="col-xs-4">Castré/Stérilisé </label>
              <td class="col-xs-8"><?=$annonceDetail[0]['castre']?></td>
            </div>
            
            <div class="rowD" >
              <label class="col-xs-4"><?=$typeA.' le'?> </label>
              <td class="col-xs-8"><?=$annonceDetail[0]['datePT']?></td>
            </div>
            <div class="rowD" >
              <label class="col-xs-4"><?=$typeA.' à'?> </label>
              <td class="col-xs-8" >
                <?=$annonceDetail[0]['rue'].'<br>'?>
                <?=$annonceDetail[0]['arrondissement'].' Marseille'?>
                
              </td>
            </div>
            <div class="rowD" >
          
              <td class="col-xs-8" colspan="2"  id="backColor" >
                <?php 
                if(empty($annonceDetail[0]['description'])==false)
                {
                  echo '<strong >'."Plus d'information sur cette annonce :".'</strong>'; 
                  echo '<p>'. $annonceDetail[0]['description'].'</p>'; 
                }
                else echo "Il n'y a pas d'informations complémentaires."; 
                 ?>
                  
              </td>
            </div>          
                                                                                    
          
        </div>
      </div>
    </div>
    
    <div class="row info operation corrige ">
      

        <div class="col-md-1"></div>
        <div class="col-xs-12 col-md-3 supprimerD"> 
          <a href="#" onclick="confirmation();">
            <span class="glyphicon glyphicon-trash"></span>
          Supprimer cette annonce </a>
        </div>
    </div>

        <!-- afficher l'adresse par google map-->
		<div>
			
		</div>

        <!-- cet endroit pour les commentaires avec l'option de supprimer -->
        <!-- le revenu d'ajax-->
        <span id="id_chat" style="display: none;"><?=$annonceDetail[0]['idchat']?></span>
        <div id="commentairesAdmin">
        
        	
        </div>







		<?php if (preg_match('#trouvé#',$typeA)):?>
   
			<script >		
		     document.getElementById("cap").style="background-color:#69C864;";
		      document.getElementById("tr").style.border="2px solid green";
		      document.getElementById("talblCTr").style.border="2px solid green";
	
			</script>	
		<?php endif;?>		
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
   </script>		
   <script type="text/javascript">
   	 function confirmation()
   	 	 {
			if (confirm("Voulez-vous vraiment supprimer cette annonce ?" ))
				 {
					window.location.href = "supprimerA.php?id=<?=$idchat?>&type=<?=$type?>"; 
				 }
		}
	function commentairesAdmin()
		{
			$.ajax({

		     type: "POST",
		     url: "commentairesAdmin.php",
		     data: 'id_chat='+$('#id_chat').html(), 
		     error: function(errorData) {console.log($('#id_chat').html())},
		     success: function(data){
		     	console.log('success des commentaires'); 
		     	$('#commentairesAdmin').html(data); 
		     }

			}); 
		}	
$(commentairesAdmin); 
  

    
   </script>   

