<!DOCTYPE html>
<html>
	<head>
			<title><?=$templateTitle?></title>
			<link rel="shortcut icon" type="image/x-icon" href="img/parDefaut0.jpg" />
			<meta charset="utf-8">
			<meta http-equiv="“content-language”" content="“fr-fr”">
			<meta name="robots" content="index, follow">     
			<meta name="author" content="Hmzeh Bassissi développeur web à Marseille"> 
			<meta name="description" content="<?=$templateDescription?>" >
			<meta name="keywords" content="<?=$templateKeywords?>">

			<link href="https://fonts.googleapis.com/css?family=Cutive+Mono|Fira+Sans|Fjalla+One|Merriweather|Roboto+Mono|Roboto+Slab&display=swap" rel="stylesheet"> 
			<link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet"> 
			<link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One&display=swap" rel="stylesheet"> 
			 <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
			 <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Shrikhand" rel="stylesheet"> 
			<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">   
	        <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous">
			</script>
	        <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous">
	        </script>

			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	    	<link rel="stylesheet" type="text/css" href="css/style.css">
	    	<link media="print" href="print.css" />	
	</head>



<div class="container-fluid">
	<div class="row info">
        <div class="col-xs-12 col-md-4 ">
			<div id="img1" class="img1">

				<img  src=<?=$annonceDetail[0]['url']?> style=" width:100%;" title='<?=$annonceDetail[0]['name'].', '.$sex.' '.$typeA.' le ' .$annonceDetail[0]['datePT'] ?>'>
			</div>

			<div class="contact">
			
				 	<h5><?=$messageContact?></h5>
				 	<p>
				 		   Téléphone :
				 		   <span>  <?=$annonceDetail[0]['phone']?></span>
				 	</p>
			
			</div>

	    </div>   
			
        
		<div class="col-xs-12 col-md-7 detail" >
				<div  style="width: 100%; " >
					<h4 id="cap" ><?=$annonceDetail[0]['name'].', '?> <?=$sex.' '?><?=$typeA?> </h4>
					
						<div class="rowD" >
							<label class="col-xs-4">Publié le </label>
							<td class="col-xs-8"><?=$datePublie?></td>
						</div>
						<div class="rowD" >
							<label class="col-xs-4">Sexe </label>
							<td class="col-xs-8"><?php if($annonceDetail[0]['sex']=='male') echo 'mâle'; else echo $annonceDetail[0]['sex']; ?></td>
						</div>
						<div class="rowD" >
							<label class="col-xs-4">Race </label>
							<td class="col-xs-8"><span id=Minuscule><?=$annonceDetail[0]['race']?></span></td>
						</div>
						<div class="rowD" >
							<label class="col-xs-4">Couleur </label>
							<td><?=$annonceDetail[0]['couleurs']?></td class="col-xs-8">
						</div>

						<div class="rowD" >
							<label class="col-xs-4">Poils </label>
							<td class="col-xs-8"><?=$annonceDetail[0]['poils']?></td>
						</div>
						<div class="rowD" >
							<label class="col-xs-4">Pelage </label>
							<td class="col-xs-8"><?=$annonceDetail[0]['pelage']?></td>
						</div>

						<div class="rowD" >
							<label class="col-xs-4">Castré/Stérilisé </label>
							<td class="col-xs-8"><?=$annonceDetail[0]['castre']?></td>
						</div>
						
						<div class="rowD" >
							<label class="col-xs-4"><?=$typeA.' le'?> </label>
							<td class="col-xs-8"><?=$annonceDetail[0]['datePT']?></td>
						</div>
						<div class="rowD" >
							<label class="col-xs-4"><?=$typeA.' à'?> </label>
							<td class="col-xs-8" >
								<?=$annonceDetail[0]['rue'].'<br>'?>
								<?=$annonceDetail[0]['arrondissement'].' Marseille'?>
								
							</td>
						</div>
						<div class="rowD" >
					
							<td class="col-xs-8" colspan="2"  id="backColor" >
								<?php 
								if(empty($annonceDetail[0]['description'])==false)
								{
									echo '<strong >'."Plus d'information sur cette annonce :".'</strong>'; 
									echo '<p>'. $annonceDetail[0]['description'].'</p>'; 
								}
								else echo "Il n'y a pas d'informations complémentaires."; 
								 ?>
								 	
							</td>
						</div>					
																																										
					
				</div>
			</div>
    </div>





    

	 <script Language="JavaScript">
	//dynamicdrive.com
	function printit(){

	    window.print() ;

	}
	printit(); 
	 
	</script>  
</div>
