<!DOCTYPE html>
<html lang="fr">
	<head>
	<meta charset="utf-8">	
	<meta http-equiv="“content-language”" content="“fr-fr”">	
	<meta  name="viewport" content="width=device-width, initial-scale=1">
	<meta name="apple-mobile-web-app-title" content="Chat Perdu">
	<meta name="application-name" content="Chat Perdu">
	<meta name="robots" content="index, follow">

	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link rel="stylesheet" type="text/css" href="css/style.css">
	<?php if (empty($templateTitle)==true)
			$templateTitle="chats perdus ou trouvés à Marseille France";
	?>
	<?php if (empty($templateDescription)==true)
			$templateDescription="voir les annonces : mâles ou femelles chats perdus ou trouvés Marseille 13 France. ";
	?>
	<?php if (empty($templateKeywords)==true)
			$templateKeywords="chat, perdu, Marseille, France, annonces, publier";
	?>

		<title><?=$templateTitle?></title>
		<link rel="shortcut icon" type="image/x-icon" href="img/parDefaut0.jpg" />
		
  
		<meta name="author" content="Hmzeh Bassissi développeur web à Marseille"> 
		<meta name="description" content="<?=$templateDescription?>" >
		<meta name="keywords" content="<?=$templateKeywords?>">	
		
		<link href="https://fonts.googleapis.com/css?family=Cutive+Mono|Fira+Sans|Fjalla+One|Merriweather|Roboto+Mono|Roboto+Slab&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Rubik+Mono+One&display=swap" rel="stylesheet"> 
		 <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
		 <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Shrikhand" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">   
        <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous">
		</script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous">
        </script>	

	</head>

	<body>

		<header>
	
			
			
			<center>
				<h2><a href="index.php" > Chat perdu Marseille</a></h2>
			</center>
			<span class="glyphicon glyphicon-th-list btn " id="logoListe"></span>
			<nav class="navbar" >

				
					<a href="index.php"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
					<a href="rechercherPar.php">Rechercher</a>
					<a href="perdus.php">Perdus</a>
					<a href="trouves.php">Trouvés</a>
					<a href="publier.php">Publier une annonce</a>
					<a href="retrouves.php">Retrouvés</a>
					<a href="photos.php">Photos des chats</a>
					<a href="meilleur.php">Ce site est le meilleur</a>
					<a href="contact.php">Contact</a>
				
			</nav>	
		</header>

		<main class="corp">


            <!--Boite de Nouvelles-->
           
            <div style="background-color: black; " >
            	
                 <marquee  BEHAVIOR="scroll" scrollamount="4" style="padding:5px; " >
                 	<?php include 'marquee.php';  ?>
                 </marquee>
            </div>	
                        
			<?php if (empty($template)!=true)
			       {
			     		include $template; 
			     	
			       }

                  else
                  {
                  		include "index.phtml"; 
                  }
			?>
		</main>
	    <footer class="container-fluid affiche">
	

				<div class="row">
					<a href="index.php" class="col-xs-1">Accueil</a>
					<a href="rechercherPar.php" class="col-xs-1">Rechercher</a>
					<a href="perdus.php" class="col-xs-1">Perdus</a>
					<a href="trouves.php" class="col-xs-1">Trouvés</a>
					<a href="publier.php" class="col-xs-2">Publier une annonce</a>
					<a href="retrouves.php" class="col-xs-1">Retrouvés</a>
					<a href="photos.php" class="col-xs-2">Photos des chats</a>
					<a href="meilleur.php" class="col-xs-2">Ce site est le meilleur</a>
					<a href="contact.php" class="col-xs-1">Contact</a>
				</div>
			
	    </footer>
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
        </script>
        <script type="text/javascript" src="javascript/javascript.js"></script>
	</body>

</html>