                <!-- messages:-->
      <div class="messageE message">
         
             <?php         
         
            if(empty($erreur)==false)
              foreach ($erreur as $key => $value)
              {
                echo '<p>'.$value.'</p>'; 
              }
                 
             if(empty($_SESSION['bien'])==false)
                {
                  echo '<p class="green">'.$_SESSION['bien'].'</p>';
                  $_SESSION['bien']=null; 
                 }
             ?>

        </div>



<div class="publicite">
  <div class="titreG paddingT">
	   <h2>Publicité <?=$id?></h2>
  </div>


<?php if($id==1): ?>
  <?php if(empty($publiciteDetail1)==false):?> 


    <div class="row">
      <div class="col-xs-12 col-md-3"></div>
      <div class="col-xs-12 col-md-6">
      	<a href="<?=$publiciteDetail1[0]['lien']?>">				    <!--loop-->
      		<video   controls="true" poster="video_poster.jpg" webkit-playsinline="true" playsinline="true" autoplay="true" muted="true" data-weborama-videoplayer="true" preload="metadata" autobuffer="false" >
      		<source src="<?=$publiciteDetail1[0]['url']?>" type="video/mp4">
      		</video>
      	</a>
      </div>
      <div class="col-xs-12 col-md-3"></div>
    </div>
  <?php else: ?>
    <div class="row">
        <div class="col-xs-12 col-md-3"></div>
        <div class="col-xs-12 col-md-6 textCenter">
          <a href="<?=$publiciteDetail[0]['lien']?>">                    <!--loop-->
          <video  controls="true" poster="video_poster.jpg" webkit-playsinline="true" playsinline="true" autoplay="true" muted="true" data-weborama-videoplayer="true" preload="metadata" autobuffer="false" >
          <source src="<?=$publiciteDetail[0]['url']?>" type="video/mp4">
          </video>
          </a>
        </div> 
        <div class="col-xs-12 col-md-3"></div>
    </div>
  <?php endif; ?> 
  <div class="modiV">
  	<form method="POST" action="publicite.php?id=<?=$id?>" enctype="multipart/form-data">
  			<h2 class="h3">Changez votre publicité</h2>

  			<div class="row paddingPub">
            <div class="col-xs-12 col-md-4 paddingRightPub">
    			     <label for="uplaodI" >Modifiez la vidéo </label> 
            </div>
            <div class="col-xs-12 col-md-6">    
               <input type="file" name="uplaodI" id="uplaodI" class="padd">
            </div>   
         </div>
         <div class="row paddingPub">
            <div class="col-xs-12 col-md-4 paddingRightPub">  
              <label for="lien">Modifiez le lien</label>
            </div>  

            <?php if(empty($publiciteDetail1)==false):?> 
                <div class="col-xs-12 col-md-6 paddingLeftPub ">  
                  <input type="text" class="form-control" id="lien" name="lien" value="<?=$publiciteDetail1[0]['lien']?>">
                 </div> 
            <?php else: ?>
                 <div class="col-xs-12 col-md-6 paddingLeftPub">  
                   <input type="text" name="lien" class="form-control"  value="<?=$publiciteDetail[0]['lien']?>">
                  </div>  
            <?php endif;?>     
           </div>
           <div class="row paddingPub">  
             <div class="col-md-1"></div>
             <div class="col-xs-12 col-md-8 paddingRightPub">
                <label for="vide"> <span>Voulez-vous que cette publicité soit vide et invisible devant l'utilisateur ?</span></label>
                <select name="vide" >
                    <option value="Non">Non</option>
                	<option value="Oui">Oui</option>
                </select>
             </div> 
           </div> 
            
              <input type="submit" name="changer" value="Enregistrer" onclick="message()" class="btn btn-primary" style="margin-bottom: 10px; ">

  		
  	</form>
  <div> 
<?php endif;?>  
<?php if(in_array($id, [2,3,4])): ?> 
   <?php if(empty($publiciteDetail1)==false):?> 
    <div class="row">
      <div class="col-xs-12 col-md-3"></div>
      <div class="col-xs-12 col-md-6 paddingIPub">
          <a href="<?=$publiciteDetail1[0]['lien']?>">                    <!--loop-->
              <img width="100%" height="250" src="<?=$publiciteDetail1[0]['url']?>"  style="margin-bottom: 10px;">
          </a>
      </div>  
    </div>
   <?php else: ?>
    <div class="row">
      <div class="col-xs-12 col-md-3"></div>
      <div class="col-xs-12 col-md-6 paddingIPub ">
        <a href="<?=$publiciteDetail[0]['lien']?>">                    <!--loop-->
            <img width="100%" height="250" src="<?=$publiciteDetail[0]['url']?>" style="margin-bottom: 10px;" >
        </a>
      </div>

     </div>
  <?php endif; ?> 
  <div class="modiV">
    <form method="POST" action="publicite.php?id=<?=$id?>" enctype="multipart/form-data">
            <h2 class="h3">Changez votre publicité</h2>
            <div class="row paddingPub">
               <div class="col-xs-12 col-md-4 paddingRightPub">
                  <label for="uplaodI">Modifiez la photo </label>
               </div>
               <div class="col-xs-12 col-md-6">               
                <input type="file" name="uplaodI" id="uplaodI" class="padd">
               </div> 
            </div>
            <div class="row paddingPub">
              <div class="col-xs-12 col-md-4 paddingRightPub">
                <label for="lien">Modifiez le lien</label>
              </div>  
              <?php if(empty($publiciteDetail1)==false):?>
              <div class="col-xs-12 col-md-6 paddingLeftPub "> 
                  <input type="text" id="lien" name="lien" value="<?=$publiciteDetail1[0]['lien']?>" class="form-control">
              </div>    
              <?php else: ?>
              <div class="col-xs-12 col-md-6 paddingLeftPub ">  
                   <input type="text" name="lien" value="<?=$publiciteDetail[0]['lien']?>" class="form-control">
              </div>     
              <?php endif;?>     
            </div>
           <div class="row paddingPub"> 
             <div class="col-md-1"></div>
             <div class="col-xs-12 col-md-8 paddingRightPub">     
              <label for="vide"> <span>Voulez-vous que cette publicité soit vide et invisible devant l'utilisateur ?</span></label>              
              <select name="vide">
                  <option value="Non">Non</option>
                  <option value="Oui">Oui</option>
              </select>
              </div> 
            </div>

            <input type="submit" name="changer" value="Enregistrer" onclick="message()" class="btn btn-primary" style="margin-bottom: 10px; ">
        
    </form>
  </div>
<?php endif;?>      
</div>

<!-- javascript-->
<script type="text/javascript">
        function message()
        {



          if(confirm("Voulez-vous vraiment modifier votre publicité ?"))
          {
            var v=1;
             
          }
          if(v!==1)
          {
            document.write("Vous avez renoncé à enregistrer !");
            
            setTimeout(function() {window.location.assign("publicite.php?id=<?=$id?>");},2500);                 
                        
          }  
        }
        
    </script>