
			        <!-- messages:-->
	    <div class="messageE message">
	       
             <?php         
         
             if(empty($_SESSION['messageSA'])==false)
             	echo '<p >'.$_SESSION['messageSA'].'</p>'; 

	             $_SESSION['messageSA']=null; 
	        
	                     
             ?>

        </div>

<section class=" container-fluid">
			<?php if (empty($annoncePs)!==true):?>
					<?php 
						$counter=0; 
						foreach ($annoncePs as $key)
						$counter+=1; 
					    if($counter==1|$counter==0)
						    	$message=$counter.' chat perdu'; 
						else
						    	$message=$counter.' chats perdus';
			        ?>
				
					 <h2 class="row perduL perduH2 textCenter" >
					 		<?php if($counter>=0):?>	       
			        			Nous avons <?=$message?> 
			        		<?php endif;?>	
					 </h2>	
					

						<?php foreach($annoncePs as $key =>$annonce): ?>
                         <div class="container-fluid perduBox textCenter">
							<div class=" divP row perdu "  data_id="<?=$key?>" id="divP<?=$key?>" >
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte';
										$type='perdue';  
									}
									else
									{
										$sex='chat';
										$type='perdu'; 
									}
								?>

								<div class="col-xs-12 col-md-3"><img src=<?=$annonce['url']?>  style=" width:150px; height: 140px; "  class="img-rounded" title='<?=$annonce['name'].', '.$sex.' '.$type.' le ' .$annonce['datePT'] ?>'></div>


								<div class="col-xs-12 col-md-6 perduText">
									<p><?='<span>'.'<strong>'.$annonce['name'].'</strong>'.'</span>'.', '.$sex.' <span style="color:red">'.$type.'</span> le '.$annonce['datePT']?></p>
									<p><?='<strong>Lieu :</strong>'.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</div>
								
								<div class="col-xs-12 col-md-3 perduLien">
								   
									<a href=detailA.php?idchat=<?=$annonce['idchat']?>&type=perdu class="btn btn-danger subP " data_id="<?=$key?>"  >Voir cette annonce </a>
								</div>
							</div>
                        </div>
                        <?php  endforeach;?>
					
				
			<?php endif;?>